version: "3.9"

services:
  app:
    build: ./
    command: [ "./bin/entrypoint.sh" ]
    network_mode: "host"
    devices:
      - /dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
    volumes:
      - .:/app:delegated
      - /run/dbus/:/run/dbus/
      - /dev/shm:/dev/shm
